workflows:
  sportmen-ios-only:
    name: Sportmen iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Recreate iOS Directory
        # Windows'taki dosyalarına dokunmuyoruz, sadece Mac'te temizliyoruz
        script: |
          rm -rf ios
          flutter create --platforms=ios .
      - name: Build iOS
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT > service-account.json
          # Artık podhelper.rb yolunu elle belirtmemize gerek yok
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa