workflows:
  sportmen-ios-only: # İsmi sadece iOS olduğunu belli edecek şekilde değiştirdik
    name: Sportmen iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Update iOS platform version
        script: |
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/g" ios/Podfile
      - name: Build iOS
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT > service-account.json
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa