workflows:
  sportmen-ios-android:
    name: Sportmen Build
    environment:
      flutter: stable
      xcode: latest
      # Build ortamı için JVM ayarları
      GRADLE_OPTS: -Xmx4096m -XX:MaxMetaspaceSize=1024m
      JVM_OPTS: -Xmx4096m
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android
        # Buradaki --no-daemon flag'i bellek şişmesini engeller
        script: flutter build appbundle --release --no-daemon
      - name: Build iOS
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT > service-account.json
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa