// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNNgU0kFwrZNcSHHNCpL0kdcCJRtSOdQw',
    appId: '1:1054757545170:web:208dc60aec60131e7e790b',
    messagingSenderId: '1054757545170',
    projectId: 'spor-4cf48',
    authDomain: 'spor-4cf48.firebaseapp.com',
    storageBucket: 'spor-4cf48.firebasestorage.app',
    measurementId: 'G-HPQZ3X0GTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwf_SVda5oN5lBOGXXSEeClUzxPuzSnp8',
    appId: '1:1054757545170:android:f3c9b6897fcb5cc77e790b',
    messagingSenderId: '1054757545170',
    projectId: 'spor-4cf48',
    storageBucket: 'spor-4cf48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSXuWH1pNaNAOImTj1ObnJQoKYjAGrmmQ',
    appId: '1:1054757545170:ios:501a1f3c5bdcab947e790b',
    messagingSenderId: '1054757545170',
    projectId: 'spor-4cf48',
    storageBucket: 'spor-4cf48.firebasestorage.app',
    iosBundleId: 'com.example.spor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSXuWH1pNaNAOImTj1ObnJQoKYjAGrmmQ',
    appId: '1:1054757545170:ios:501a1f3c5bdcab947e790b',
    messagingSenderId: '1054757545170',
    projectId: 'spor-4cf48',
    storageBucket: 'spor-4cf48.firebasestorage.app',
    iosBundleId: 'com.example.spor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNNgU0kFwrZNcSHHNCpL0kdcCJRtSOdQw',
    appId: '1:1054757545170:web:8c04e7479580def47e790b',
    messagingSenderId: '1054757545170',
    projectId: 'spor-4cf48',
    authDomain: 'spor-4cf48.firebaseapp.com',
    storageBucket: 'spor-4cf48.firebasestorage.app',
    measurementId: 'G-T8S3W85QD7',
  );
}
